apiVersion: v2
appVersion: "2022.1.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.14.5
description: Minecraft Bedrock Dedicated Server
home: https://github.com/Dyllan20000alfa/apps/tree/master/charts/incubator/minecraft-bedrock
icon: https://raw.githubusercontent.com/Dyllan2000alfa/apps/minecraft-bedrock/charts/incubator/minecraft-bedrock/icon.png
keywords:
  - minecraft
kubeVersion: ">=1.16.0-0"
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: minecraft-bedrock
sources:
  - https://github.com/itzg/docker-minecraft-server
  - https://hub.docker.com/r/itzg/minecraft-server
version: 0.0.6
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
