image:
  repository: itzg/minecraft-server
  tag: 2022.1.1@sha256:b54073d712c0b909c797be85582472d01dae0f7b64c85397f45165955ad2ad21
  pullPolicy: IfNotPresent

imageJava11:
  repository: itzg/minecraft-server
  tag: 2022.1.1-java11@sha256:f8e649fca2efd27c2aa7a3382aeb8ce8f8c9a55221584392d66631ae32233bfb
  pullPolicy: IfNotPresent

imageJava8:
  repository: itzg/minecraft-server
  tag: 2022.1.1-java8-multiarch@sha256:3fbcf823a00e84691e085e2102670bbdfc1cce00d69d5c4647a620305d5de102
  pullPolicy: IfNotPresent

imageSelector: "image"

env:
  EULA: "FALSE"
  VERSION: "LATEST"
  TYPE: "VANILLA"
  DIFFICULTY: easy
  MAX_PLAYERS: 20
  MAX_WORLD_SIZE: 10000
  ALLOW_NETHER: true
  ANNOUNCE_PLAYER_ACHIEVEMENTS: true
  ENABLE_COMMAND_BLOCK: false
  FORCE_GAMEMODE: false
  GENERATE_STRUCTURES: true
  HARDCORE: false
  MAX_BUILD_HEIGHT: 256
  MAX_TICK_TIME: 60000
  SPAWN_ANIMALS: true
  SPAWN_MONSTERS: true
  SPAWN_NPCS: true
  VIEW_DISTANCE: 10
  MODE: survival
  MOTD: "Welcome to Minecraft on TrueNAS Scale!"
  PVP: false
  LEVEL_TYPE: DEFAULT
  LEVEL: world
  ONLINE_MODE: true
  MEMORY: 2048M

persistence:
  data:
    enabled: true
    mountPath: "/data"

service:
  main:
    ports:
      main:
        port: 25565
        targetPort: 25565
