apiVersion: v2
appVersion: "a8"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.18
description: Minecraft Java Dedicated Server
home: https://github.com/truecharts/apps/tree/master/charts/incubator/minecraft-java
icon: https://raw.githubusercontent.com/Dyllan2000alfa/apps/minecraft/charts/incubator/minecraft-java/icon.png
keywords:
  - minecraft
kubeVersion: ">=1.16.0-0"
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: minecraft-java
sources:
  - https://github.com/itzg/docker-minecraft-server
  - https://hub.docker.com/r/itzg/minecraft-server
version: 0.0.4
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
