image:
  repository: itzg/minecraft-server
  tag: 2021.25.0-java8-multiarch
  pullPolicy: IfNotPresent

env:
  eula: "FALSE"
  version: "LATEST"
  type: "VANILLA"
  difficulty: easy
  maxPlayers: 20
  maxWorldSize: 10000
  allowNether: true
  announcePlayerAchievements: true
  enableCommandBlock: false
  forcegameMode: false
  generateStructures: true
  hardcore: false
  maxBuildHeight: 256
  maxTickTime: 60000
  spawnAnimals: true
  spawnMonsters: true
  spawnNPCs: true
  viewDistance: 16
  gameMode: survival
  motd: "Welcome to Minecraft on TrueNAS Scale!"
  pvp: false
  levelType: DEFAULT
  worldSaveName: world
  onlineMode: true
  memory: 1024M

persistence:
  data:
    enabled: true
    mountPath: "/data"

service:
  main:
    ports:
      main:
        port: 25565
        targetPort: 25565
