image:
  repository: aeonlucid/impostor
  pullPolicy: IfNotPresent
  tag: 1.6.0@sha256:fbfe8e95db116771c488570e20834f3038501741745db60031e05b282fce00c3

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  IMPOSTOR_Server__PublicIp: "127.0.0.1"
  IMPOSTOR_Server__ListenIp: "0.0.0.0"
  IMPOSTOR_AntiCheat__Enabled: true
  IMPOSTOR_AntiCheat__BanIpFromGame: true
  IMPOSTOR_Debug__GameRecorderEnabled: true
  IMPOSTOR_Debug__GameRecorderPath: ""

service:
  main:
    ports:
      main:
        protocol: UDP
        port: 22023
        targetPort: 22023

startupProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1

persistence:
  config:
    enabled: true
    mountPath: "/app"