image:
  repository: itzg/minecraft-bedrock-server
  tag: 2022.1.0@sha256:fd753dd3fbee83944baf4982e481a7d48a4d52387d6bd3916628335e8bdb4ed6
  pullPolicy: Always

env:
  UID: 568
  GID: 568
  EULA: "FALSE"
  VERSION: "LATEST"
  SERVER_NAME: "Dedicated Server on TrueNAS Scale!"
  SERVER_PORT: 19132
  SERVER_PORT_V6: 19133
  GAMEMODE: "survival"
  DIFFICULTY: "easy"
  LEVEL_TYPE: "DEFAULT"
  ALLOW_CHEATS: false
  MAX_PLAYERS: 10
  ONLINE_MODE: true
  WHITE_LIST: false
  VIEW_DISTANCE: 32
  TICK_DISTANCE: 4
  PLAYER_IDLE_TIMEOUT: 30
  MAX_THREADS: 8
  LEVEL_NAME: "Bedrock level"
  LEVEL_SEED: ""
  DEFAULT_PLAYER_PERMISSION_LEVEL: "member"
  TEXTUREPACK_REQUIRED: false
  SERVER_AUTHORITATIVE_MOVEMENT: server-auth
  PLAYER_MOVEMENT_SCORE_THRESHOLD: 20
  PLAYER_MOVEMENT_DISTANCE_THRESHOLD: 0.3
  PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS: 500
  CORRECT_PLAYER_MOVEMENT: false

persistence:
  config:
    enabled: true
    mountPath: "/data"

service:
  main:
    ports:
      main:
        port: 19132
        targetPort: 19132
        protocol: UDP

probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    enabled: false

  # -- Redainess probe configuration
  # @default -- See below
  readiness:
    enabled: false

  # -- Startup probe configuration
  # @default -- See below
  startup:
    enabled: false
