image:
  repository: bitnami/nginx
  pullPolicy: IfNotPresent
  tag: 1.20.2@sha256:4f0aec95fcce33f355edb796f11d65a4299f9605066d0b0a786d7e238e51994e

env: {}

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 8080

persistence:
  config:
    enabled: true
    mountPath: "/opt/bitnami/nginx/"
  html:
    enabled: true
    mountPath: "/app"
