image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 1.20.2-alpine@sha256:bb129a712c2431ecce4af8dde831e980373b26368233ef0f3b2bae9e9ec515ee

env: {}

service:
  main:
    ports:
      main:
        targetPort: 80
        port: 80

persistence:
  config:
    enabled: true
    mountPath: "/etc/nginx/"
  html:
    enabled: true
    mountPath: "/usr/share/nginx/html"
