image:
  repository: itzg/minecraft-server
  tag: 21.26.0@sha256:75c9c1555461a9e3df22c99e50ed8c6767adaa3364c8a481dac7bf0d5a296d4c
  pullPolicy: Always

portal:
  enabled: false

env:
  EULA: "FALSE"
  VERSION: "LATEST"
  TYPE: "VANILLA"
  DIFFICULTY: easy
  MAX_PLAYERS: 20
  MAX_WORLD_SIZE: 10000
  ALLOW_NETHER: true
  ANNOUNCE_PLAYER_ACHIEVEMENTS: true
  ENABLE_COMMAND_BLOCK: false
  FORCE_GAMEMODE: false
  GENERATE_STRUCTURES: true
  HARDCORE: false
  MAX_BUILD_HEIGHT: 256
  MAX_TICK_TIME: 60000
  SPAWN_ANIMALS: true
  SPAWN_MONSTERS: true
  SPAWN_NPCS: true
  VIEW_DISTANCE: 16
  MODE: survival
  MOTD: "Welcome to Minecraft on TrueNAS Scale!"
  PVP: false
  LEVEL_TYPE: DEFAULT
  LEVEL: world
  ONLINE_MODE: true
  MEMORY: 2048M

persistence:
  data:
    enabled: true
    mountPath: "/data"

service:
  main:
    ports:
      main:
        port: 25565
        targetPort: 25565
