image:
  repository: wolveix/satisfactory-server
  pullPolicy: IfNotPresent
  tag: v1.2.3@sha256:5860dbac9fc8cb2e6010b69e60e633d06e25e2a0152f8858a8f23acda7c3c719

env:
  AUTOPAUSE: true
  AUTOSAVEINTERVAL: 300
  AUTOSAVENUM: 3
  AUTOSAVEONDISCONNECT: true
  CRASHREPORT: true
  DEBUG: false
  DISABLESEASONALEVENTS: false
  MAXPLAYERS: 4
  SERVERBEACONPORT: 15000
  SERVERGAMEPORT: 7777
  SERVERIP: "0.0.0.0"
  SERVERQUERYPORT: 15777
  SKIPUPDATE: false
  STEAMBETA: false

service:
  main:
    ports:
      main:
        targetPort: 7777
        port: 7777
        protocol: UDP
  beacon:
    enabled: true
    ports:
      beacon:
        enabled: true
        port: 15000
        targetPort: 15000
        protocol: UDP
  query:
    enabled: true
    ports:
      query:
        enabled: true
        port: 15777
        targetPort: 15777
        protocol: UDP
