apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.21
description: Minecraft Bedrock Dedicated Server
home: https://github.com/Dyllan20000alfa/apps/tree/master/charts/incubator/minecraft-bedrock
icon: https://raw.githubusercontent.com/Dyllan2000alfa/apps/minecraft-bedrock/charts/incubator/minecraft-bedrock/icon.png
  - minecraft
kubeVersion: ">=1.16.0-0"
maintainers:
- email: dyllan@tinoco.casa
  name: Dyllan Tinoco
name: minecraft-bedrock
sources:
  - https://github.com/itzg/docker-minecraft-server
  - https://hub.docker.com/r/itzg/minecraft-server
version: 0.0.4
